import Atom from "../../media/stake/Gaia.svg";
// import Osmosis from "../../media/stake/Osmosis.svg";
// import Juno from "../../media/stake/Juno.svg";
// import Cyber from "../../media/stake/Cyber.svg";
// import Starname from "../../media/stake/Starname.svg";
// import Akash from "../../media/stake/Akash.svg";
// import Emoney from "../../media/stake/Emoney.svg";
// import Evmos from "../../media/stake/Evmos.svg";
// import Sifchain from "../../media/stake/Sifchain.svg";
// import Sentinel from "../../media/stake/Sentinel.svg";
// import Stargaze from "../../media/stake/Stargaze.svg";
// import Kava from "../../media/stake/Kava.svg";
// import Ixo from "../../media/stake/Ixo.svg";
// import Secret from "../../media/stake/Secret.svg";
// import Regen from "../../media/stake/Regen.svg";
// import Kichain from "../../media/stake/Kichain.svg";
// import Likecoin from "../../media/stake/Likecoin.svg";
// import Konstellation from "../../media/stake/darc.svg";
// import Cheq from "../../media/stake/cheq.svg";
// import Bitcanna from "../../media/stake/bitcanna.svg";
// import Band from "../../media/stake/Band.svg";
// import Provenance from "../../media/stake/Provenance.svg";
// import Vidulum from "../../media/stake/vidulum.svg";
// import Omniflix from "../../media/stake/omniflix.svg";
// import Chihuahua from "../../media/stake/Juno.svg";

export const STAKES = [
  // {
  //   id: "s1",
  //   image: `${Osmosis}`,
  //   name: "Osmosis",
  //   denom: "OSMO",
  //   api: "",
  //   keplr: "osmosis",
  //   ping: "osmosis",
  //   price: "",
  //   address: "osmovaloper1083svrca4t350mphfv9x45wq9asrs60c6rv0j5",
  // },
  {
    id: "s2",
    image: `${Atom}`,
    name: "Atom",
    denom: "ATOM",
    api: "https://api.cosmostation.io",
    keplr: "cosmoshub",
    ping: "cosmos",
    price:
      "https://api.coingecko.com/api/v3/simple/price?ids=cosmos&vs_currencies=usd",
    address: "cosmosvaloper1083svrca4t350mphfv9x45wq9asrs60cdmrflj",
  },
  // {
  //   id: "s3",
  //   image: `${Juno}`,
  //   name: "Juno",
  //   denom: "JUNO",
  //   api: "",
  //   keplr: "juno",
  //   ping: "juno",
  //   price: "",
  //   address: "junovaloper1083svrca4t350mphfv9x45wq9asrs60cpqzg0y",
  // },
  // {
  //   id: "s4",
  //   image: `${Starname}`,
  //   name: "Starname",
  //   denom: "IOV",
  //   api: "",
  //   keplr: "iov-mainnet",
  //   ping: "starname",
  //   price: "",
  //   address: "starvaloper1pdqlmncych8uzsfdnsptv7s0wpazc0rgv7zc6h",
  // },
  // {
  //   id: "s5",
  //   image: `${Cyber}`,
  //   name: "Cyber",
  //   denom: "BOOT",
  //   api: "",
  //   keplr: "bostrom",
  //   ping: "bostrom",
  //   price: "",
  //   address: "bostromvaloper1g65rmjkeuy5rywx04s4fvwfylmlz98vq4gzln5",
  // },
  // {
  //   id: "s6",
  //   image: `${Akash}`,
  //   name: "Akash",
  //   denom: "AKASH",
  //   api: "",
  //   keplr: "akashnet",
  //   ping: "akash-network",
  //   price: "",
  //   address: "akashvaloper1g5qqaxu89qk54ex3zh6tus0a8ta2sj4fuejw9a",
  // },
  // {
  //   id: "s7",
  //   image: `${Emoney}`,
  //   name: "Emoney",
  //   denom: "NGM",
  //   api: "",
  //   keplr: "emoney",
  //   ping: "e-money",
  //   price: "",
  //   address: "emoneyvaloper16dc379m0qj64g4pr4nkl7ewak52qy2srpe6lxp",
  // },
  // {
  //   id: "s8",
  //   image: `${Evmos}`,
  //   name: "Evmos",
  //   denom: "EVMOS",
  //   api: "",
  //   keplr: "evmos",
  //   ping: "evmos",
  //   price: "",
  //   address: "evmosvaloper1rv94jqhlhx6makfwl6qs390e4shg32m6w6dxzy",
  // },
  // {
  //   id: "s9",
  //   image: `${Sifchain}`,
  //   name: "Sifchain",
  //   denom: "ROWAN",
  //   api: "",
  //   keplr: "sifchain",
  //   ping: "sifchain",
  //   price: "",
  //   address: "sifvaloper1083svrca4t350mphfv9x45wq9asrs60cyssqu6",
  // },
  // {
  //   id: "s10",
  //   image: `${Sentinel}`,
  //   name: "Sentinel",
  //   denom: "DVPN",
  //   api: "",
  //   keplr: "sentinel",
  //   ping: "sentinel",
  //   price: "",
  //   address: "sentvaloper1083svrca4t350mphfv9x45wq9asrs60cv37gc8",
  // },
  // {
  //   id: "s11",
  //   image: `${Stargaze}`,
  //   name: "Stargaze",
  //   denom: "STARS",
  //   api: "",
  //   keplr: "stargaze",
  //   ping: "stargaze",
  //   price: "",
  //   address: "starsvaloper1v8yp5x5kfex4wep2pfuuyw68cn2lst3ksl0gss",
  // },
  // {
  //   id: "s12",
  //   image: `${Kava}`,
  //   name: "Kava",
  //   denom: "KAVA",
  //   api: "https://api-kava.cosmostation.io",
  //   keplr: "kava",
  //   ping: "kava",
  //   price: "",
  //   address: "kavavaloper13jyqfhak8mu4c7pydjm3eu4qla7g06a9u6xf8g",
  // },
  // {
  //   id: "s13",
  //   image: `${Ixo}`,
  //   name: "Ixo",
  //   denom: "IXO",
  //   api: "",
  //   keplr: "impacthub",
  //   ping: "ixo",
  //   price: "",
  //   address: "ixovaloper1083svrca4t350mphfv9x45wq9asrs60camel0h",
  // },
  // {
  //   id: "s14",
  //   image: `${Secret}`,
  //   name: "Secret",
  //   denom: "SCRT",
  //   api: "",
  //   keplr: "secret",
  //   ping: "secret",
  //   price: "",
  //   address: "secretvaloper18rchk5exp2vzcwrwuret5sjwpxhf4sq22ze4dr",
  // },
  // {
  //   id: "s15",
  //   image: `${Regen}`,
  //   name: "Regen",
  //   denom: "REGEN",
  //   api: "",
  //   keplr: "regen",
  //   ping: "regen",
  //   price: "",
  //   address: "regenvaloper1083svrca4t350mphfv9x45wq9asrs60ct2p9a5",
  // },
  // {
  //   id: "s16",
  //   image: `${Omniflix}`,
  //   name: "Omniflix",
  //   denom: "FLIX",
  //   api: "",
  //   keplr: "",
  //   ping: "omniflix",
  //   price: "",
  //   address: "omniflixvaloper15wshq6lmxmcn9vxky2mxf8zhstpn9ywmfc5ke5",
  // },
  // {
  //   id: "s17",
  //   image: `${Likecoin}`,
  //   name: "Likecoin",
  //   denom: "LIKE",
  //   api: "",
  //   keplr: "",
  //   ping: "likecoin",
  //   price: "",
  //   address: "cosmosvaloper16dc379m0qj64g4pr4nkl7ewak52qy2srvwj2rz",
  // },
  // {
  //   id: "s18",
  //   image: `${Kichain}`,
  //   name: "Kichain",
  //   denom: "XKI",
  //   api: "",
  //   keplr: "",
  //   ping: "kichain",
  //   price: "",
  //   address: "kivaloper1lmkzaxztjpesh0mf7qy76l5npqwc7fk3l2k57g",
  // },
  // {
  //   id: "s19",
  //   image: `${Cheq}`,
  //   name: "Cheq",
  //   denom: "CHEQ",
  //   api: "",
  //   keplr: "",
  //   ping: "cheqd",
  //   price: "",
  //   address: "cheqdvaloper1gyjqlfkrggd0uyd748fw9y5kq9xzmjqqh8848x",
  // },
  // {
  //   id: "s20",
  //   image: `${Band}`,
  //   name: "Band",
  //   denom: "BAND",
  //   api: "",
  //   keplr: "",
  //   ping: "band-protocol",
  //   price: "",
  //   address: "bandvaloper19huytqr8srz9wcdhvas5cvxddg8dtqcv6tce0s",
  // },
  // {
  //   id: "s21",
  //   image: `${Chihuahua}`,
  //   name: "Chihuahua",
  //   denom: "HUAHUA",
  //   api: "",
  //   keplr: "",
  //   ping: "chihuahua",
  //   price: "",
  //   address: "chihuahuavaloper1h6vcu4r2hx70x5f0l3du3ey2g98u9ut2tafnnv",
  // },
  // {
  //   id: "s22",
  //   image: `${Konstellation}`,
  //   name: "Konstellation",
  //   denom: "DARC",
  //   api: "",
  //   keplr: "",
  //   ping: "",
  //   price: "",
  //   address: "darcvaloper1fndgrsqmmq68ppl42wjkxh32nwpuj7vqtgep38",
  // },
  // {
  //   id: "s23",
  //   image: `${Vidulum}`,
  //   name: "Vidulum",
  //   denom: "VDL",
  //   api: "",
  //   keplr: "",
  //   ping: "vidulum",
  //   price: "",
  //   address: "vdlvaloper16pu0t4yauhduaxvu3k29w539da5d2mfxqjdmjj",
  // },
  // {
  //   id: "s24",
  //   image: `${Provenance}`,
  //   name: "Provenance",
  //   denom: "HASH",
  //   api: "",
  //   keplr: "",
  //   ping: "provenance",
  //   price: "",
  //   address: "pbvaloper10ap9fj9uq50cardmlzdj367kqg5x3ghjdp2v6p",
  // },
  // {
  //   id: "s25",
  //   image: `${Bitcanna}`,
  //   name: "Bitcanna",
  //   denom: "BCNA",
  //   api: "",
  //   keplr: "",
  //   ping: "bitcanna",
  //   price: "",
  //   address: "bcnavaloper1dl7w3myyfmnarh0t5uxmy7qe6szagz3kyhzq07",
  // },
];
